/**
 * WASM runtime — V1 stub.
 *
 * V1 uses the TypeScript simulation core for correctness.
 * V2 will replace this with the actual Rust/WASM bridge generated by wasm-bindgen.
 *
 * The interface here matches the WASMSimulationCore type in @snn/types.
 * When Rust is integrated, the TypeScript side of this bridge will not change.
 *
 * Status: V1 STUB — returns null to indicate WASM is not available.
 * The Simulator detects this and falls back to TypeScript neuron implementations.
 */

export type { WASMSimulationCore, PopulationHandle, SynapseHandle } from '@snn/types';

export type RuntimeMode = 'typescript' | 'wasm' | 'gpu';

/**
 * Attempt to load the WASM module.
 * Returns null if WASM is not available (V1 TypeScript-only mode).
 */
export async function loadWASMCore(): Promise<import('@snn/types').WASMSimulationCore | null> {
  // V2: Replace with:
  // const wasm = await import('../wasm/snn_core_bg.wasm');
  // return initWASMCore(wasm);
  return null;
}

export function getRuntimeMode(): RuntimeMode {
  // V2: detect WASM availability
  // V3: detect WebGPU availability
  return 'typescript';
}
